---
title: "Sample distributing analysis"
author: "Jannik Möllmann"
date: "2022-11-28"
output: html_document
---

```{r}
library(tidyverse)
library(ggpubr)

setwd("~/Documents/PhD/analyses/sample_distributing/")

data <- read_tsv("../sex_determination/results/data_km.tsv")

```

```{r}
set.seed(3)
data <- data %>% arrange(species, inferred_sex, population) %>% 
   mutate(rack_group = sample.int(33, size = nrow(.), replace = TRUE),
                        rack_group_alt = row_number() %% 33,
                        temp_group = as.factor(case_when(rack_group <= 11 ~ 1,
                                               rack_group <= 22 ~ 2,
                                               rack_group <= 33 ~ 3)),
                        temp_group_alt = as.factor(case_when(
                           rack_group_alt %% 3 == 0 ~ 1,
                           rack_group_alt %% 3 == 1 ~ 2,
                           rack_group_alt %% 3 == 2 ~ 3)))
```

```{r}
data <- data %>% group_by(species, population) %>% 
   mutate(rand_id = sample.int(200), rack_id = rand_id %% 33) %>% ungroup()
```

```{r, warning=FALSE, message=FALSE}

randomised <- data
combinations <- data %>% group_by(species, population) %>% summarise() %>% ungroup()

for(i in 1:nrow(combinations)){
   s <- as.character(combinations[i, "species"])
   p <- as.character(combinations[i, "population"])
   randomised <- randomised %>% full_join(
      randomised %>% dplyr::filter(species == s,population == p) %>% 
      mutate(random_id = sample.int(200)) %>%
      arrange(random_id) %>% mutate(rack_group_alt2 = rep(1:33, length.out = nrow(.)),
                                    temp_group_alt2 = as.factor(case_when(
                                       rack_group_alt2 <= 11 ~ 1,
                                       rack_group_alt2 <= 22 ~ 2,
                                       rack_group_alt2 <= 33 ~ 3))))
}


```


```{r}
ggarrange(ggplot(data, aes(x = rack_group)) + geom_bar() + ylim(c(0, 70)),
          ggplot(data, aes(x = rack_group_alt)) + geom_bar() + ylim(c(0, 70)),
          ggplot(data, aes(x = rack_id)) + geom_bar() + ylim(c(0, 70)))
```
```{r}
data %>% group_by(species, population, temp_group_alt) %>% summarise(n = n())
```

```{r}
data %>% group_by(species, population, inferred_sex, temp_group_alt) %>% summarise(n = n())
```

```{r}
ggplot(data, aes(x = temp_group_alt, fill = population)) + geom_bar() +
   facet_wrap(vars(species, inferred_sex))
```

```{r}
ggplot(data, aes(x = inferred, color = temp_group_alt)) + geom_density() +
   facet_wrap(vars(species, inferred_sex))
```


```{r}
ggplot(data, aes(x = inferred, color = temp_group_alt)) + geom_density() +
   facet_wrap(vars(species))
```


```{r}
ggplot(data, aes(x = inferred, color = temp_group_alt)) + geom_density() +
   facet_wrap(vars(species, population))
```
```{r}
for(i in 1:nrow(combinations)){
   s <- as.character(combinations[i, "species"])
   p <- as.character(combinations[i, "population"])
   print(paste0(s, " + ", p))
   tmp_data <- data %>% filter(species == s, population == p)
   
   wilcox.test(tmp_data %>% filter(temp_group_alt == 1) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 2) %>% 
                  pull(inferred))[["p.value"]] %>% print()
   wilcox.test(tmp_data %>% filter(temp_group_alt == 2) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 3) %>% 
                  pull(inferred))[["p.value"]] %>% print()
   wilcox.test(tmp_data %>% filter(temp_group_alt == 1) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 3) 
               %>% pull(inferred))[["p.value"]] %>% print()
}
```

```{r}
for(s in c("bicornis", "cornuta")){
   print(paste0(s))
   tmp_data <- data %>% filter(species == s)
   
   wilcox.test(tmp_data %>% filter(temp_group_alt == 1) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 2) %>% 
                  pull(inferred))[["p.value"]] %>% print()
   wilcox.test(tmp_data %>% filter(temp_group_alt == 2) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 3) %>% 
                  pull(inferred))[["p.value"]] %>% print()
   wilcox.test(tmp_data %>% filter(temp_group_alt == 1) %>% pull(inferred),
               tmp_data %>% filter(temp_group_alt == 3) 
               %>% pull(inferred))[["p.value"]] %>% print()
}
```

```{r}
final_data <- data %>%
   mutate(rack_group_alt = rack_group_alt + 1, 
          temp_group_alt = case_when(temp_group_alt == 1 ~ "C",
                                     temp_group_alt == 2 ~ "E",
                                     temp_group_alt == 3 ~ "F"),
          relID_v1 = str_split(relID, "-", simplify = TRUE)[,1],
          relID_v2 = as.numeric(str_split(relID, "-", simplify = TRUE)[,2])) %>% 
   arrange(rack_group_alt, relID_v1, relID_v2) %>% dplyr::select(-relID_v1, -relID_v2) %>% 
   rename(rack_ID = rack_group_alt, 
          climate_cabinet = temp_group_alt, 
          sample_ID = relID)
```

```{r}
for_weighing <- c(30, 17, 7, 20, 13, 6, 23, 28, 9, 32, 25, 
                  3, 29, 10, 12, 14, 31, 24)
rna_seq_t1 <- c(19, 2, 18)
rna_seq_t2 <- c(22, 5, 21)
rna_seq_t3 <- c(4, 15, 11)

samples_for_joe <- 
  c("GB-9", "GB-11", "KB-185", "KB-197", "NB-41", "NB-65", "SB-17", "SB-21", "NB-3", "SB-7")

final_data <- final_data %>% mutate(batch = case_when(
  rack_ID %in% for_weighing ~ "weighing",
  rack_ID %in% rna_seq_t1 ~ "rna_t1",
  rack_ID %in% rna_seq_t2 ~ "rna_t2",
  rack_ID %in% rna_seq_t3 ~ "rna_t3",
  TRUE ~ "other molecular work"
)) %>% 
  mutate(batch = ifelse(sample_ID %in% samples_for_joe, "for mays project", batch))
```

```{r}

sample_distributing_scheme <- final_data %>% dplyr::select(rack_ID, climate_cabinet, sample_ID, batch) %>% group_by(rack_ID) %>% mutate(positional_ID = 1:n()) %>% 
  dplyr::select(rack_ID, climate_cabinet, sample_ID, positional_ID, batch)

#write_tsv(final_data, "final_data.tsv")
write_tsv(sample_distributing_scheme, "sample_distributing_scheme.tsv")
```

